"""add verification fields

Revision ID: 34d1a893e602
Revises: ef5ae654f590
Create Date: 2026-06-07 18:41:23.342817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34d1a893e602'
down_revision: Union[str, Sequence[str], None] = 'ef5ae654f590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('user', sa.Column('verification_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'verification_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###