"""added True to reset_code in user

Revision ID: 98e3ec542093
Revises: be6ef0429f20
Create Date: 2026-06-09 11:41:59.573127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98e3ec542093'
down_revision: Union[str, Sequence[str], None] = 'be6ef0429f20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'reset_code',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'false'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'reset_code',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'false'::character varying"))
    # ### end Alembic commands ###
