"""added reset code func

Revision ID: be6ef0429f20
Revises: 34d1a893e602
Create Date: 2026-06-08 16:37:13.710069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be6ef0429f20'
down_revision: Union[str, Sequence[str], None] = '34d1a893e602'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_code', sa.String(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_code')
    # ### end Alembic commands ###
